# Server configuration
server:
  port: ${web.console.port:8001}
  servlet:
    contextPath: /
  sessionTimeout: 30
  tomcat:
    uriEncoding: UTF-8

# Eureka configuration
eureka:
  client:
    # 指定服务注册中心地址，类型为 HashMap，并设置有一组默认值，默认的Key为 defaultZone；默认的Value为 http://localhost:8761/eureka ，如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
    # 如果服务注册中心加入了安全验证，这里配置的地址格式为： http://<username>:<password>@localhost:8761/eureka 其中 <username> 为安全校验的用户名；<password> 为该用户的密码
    serviceUrl:
      defaultZone: ${cloud.registry.uri:http://eureka:eureka_pw@127.0.0.1:8761/eureka}
  instance:
    # 设置当前实例的主机名称
    hostname: ${web.console.ip:127.0.0.1}
    # 定义服务续约任务（心跳）的调用间隔，单位：秒 默认: 30s
    leaseRenewalIntervalInSeconds: 3
    metadataMap:
      # 设置当前实例ID
      instanceId: ${spring.application.name}:${random.value}
      # 不使用主机名来定义注册中心的地址，而使用IP地址的形式，如果设置了
      # eureka.instance.ipAddress 属性，则使用该属性配置的IP，否则自动获取除环路IP外的第一个IP地址
      preferIpAddress: false
    # 设置状态页面路径
    statusPageUrlPath: ${server.servlet.contextPath}/info
    # 设置信息页面路径
    healthCheckUrlPath: ${server.servlet.contextPath}/health

feign:
  hystrix:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

# Spring configuration
spring:
  jackson:
    # 配置mapper忽略空属性
    serializationInclusion: non_null
    # 属性命名转化策略:将驼峰转为下划线
    propertyNamingStrategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  freemarker:
    checkTemplateLocation: false
    templateLoaderPath: classpath:/templates/view
    prefix: /
    suffix: .ftl
  # datasource for oauth2 client
  datasource:
    #platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.117:3306/capital_pre_ipo?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: capital_pre_ipo
    password: capital_pre_ipo_pw
  redis:
    host: 192.168.1.117
    port: 6379
    database: 0
    password: capital_pre_ipo_pw
    timeout: 1000
    pool:
      max-active: 8
      min-idle: 1
  data:
    mongodb:
      host: 192.168.1.117
      port: 27017
      database: capital_pre_ipo
      username: capital_pre_ipo
      password: capital_pre_ipo_pw

# Application configuration
capital:
  web:
    corsMappings:
    - http://127.0.0.1:8001
    - http://localhost:8001
    - http://dev.valueonline.cn:8001
    - http://ipo.valueonline.cn:8001
    - http://ipo.valueonline.cn
    cookieDomainNamePattern: ^(?:.+\.)?(valueonline\.cn)$
    rememberMeCookieDomain: valueonline.cn
  cache:
    defaultExpireTime: 720