platform:ios,'9.0'
use_frameworks!

target 'AskDog' do

pod 'SDWebImage',:git => 'https://github.com/rs/SDWebImage.git',:branch => 'master'
pod 'Alamofire', '~> 4.0'
pod 'IQKeyboardManager', '~> 3.3.0'
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.3'
pod 'SnapKit', :git => 'https://github.com/SnapKit/SnapKit.git',:branch => 'master'
pod 'NVActivityIndicatorView', :git => 'https://github.com/ninjaprox/NVActivityIndicatorView.git',:branch => 'master'
pod 'MJRefresh', '~> 2.4.7'
pod 'ReachabilitySwift',:git => 'https://github.com/ashleymills/Reachability.swift.git',:branch => 'master'

end
