spring:
  jackson:
    serialization-inclusion: non_null
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  jpa:
    properties:
      javax.persistence.sharedCache.mode: ALL
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      hibernate.cache.region.factory_class: com.askdog.store.service.impl.cache.hibernate.redis.RedisRegionFactory