spring:
  jackson:
    serialization-inclusion: non_null
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  jpa:
    properties:
      javax.persistence.sharedCache.mode: ALL
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      hibernate.cache.region.factory_class: com.askdog.service.impl.cache.hibernate.redis.RedisRegionFactory

askdog:
  score:
    answer:
      weight:
        vote-up: 1
        vote-down: 2
        share: 4
        favorite: 6
    question:
      weight:
        viewCount: 1
        followCount: 3
        upVoteCount: 2
        downVoteCount: 2
        answerCount: 4
        commentCount: 3